apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-api-deployment
spec:
  replicas: 3  # Puedes ajustar el número de réplicas según tus necesidades
  selector:
    matchLabels:
      app: my-api
  template:
    metadata:
      labels:
        app: my-api
    spec:
      containers:
        - name: my-api-container
          image: tu-repositorio-ecr/tu-imagen-api:tag
          ports:
            - containerPort: 80