apiVersion: v1
kind: Deployment
metadata:
  name: 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: 
  template:
    metadata:
      labels:
        app: 
    spec:
      containers:
        - name: 
          image: 
          ports:
            - containerPort: 80